# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 334af8c2e2aed0647a28e9976b78304e50f9fcf7c99a8c7d614356c54043f9b0892b6f92674d13f82dfa5834803f37c8db078e60349f447538e56dfd534b57d9

test:
  secret_key_base: 8e315ed72dba463254c354bba6bf423c43c7c7a16027528d4dea0ea8a3a2b00103df6fcaa547271a7b0ba8ff1e0d5abc7987524f1e34fcc3a36a66f440b4b53e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
